---
- name: failure2
  hosts: all
  tasks:
  - name: task1
    lvol:
      vg: vgnothing
      lv: lvnothing
      size: 1g
    register: verify
    ignore_errors: True
  - name: task2
    debug: 
      var: verify
  - name: task3
    fail: 
      msg: volume group doesnt exist
    when: "'not found' in verify.err"
